# DOMAINS
postfix_domains_add:
    pattern:  /domains/add
    defaults: { _controller: PostfixDomainBundle:Domains:add }
postfix_domains_edit:
    pattern:  /domains/edit/{id}
    defaults: { _controller: PostfixDomainBundle:Domains:edit }
    requirements:
        id:  \d+
postfix_domains_delete:
    pattern:  /domains/delete/{id}
    defaults: { _controller: PostfixDomainBundle:Domains:delete }
    requirements:
        id:  \d+
postfix_domains_list:
    pattern:  /
    defaults: { _controller: PostfixDomainBundle:Domains:list }
