imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }


framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: "%kernel.debug%"
    profiler: { only_exceptions: false }


web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true