jms_security_extra:
    secure_all_services: true
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Postfix\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/
            anonymous: ~
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /administration
                failure_path: fos_login_failure
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:        %secret% # %secret% est un parametre de parameters.yml

    access_control:
        - { path: ^/administration, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
