<?php

namespace Postfix\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function UsersQuickList($nombreParPage , $page)
	{
		if ($page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
	 
		$query = $this->createQueryBuilder('a')
								->orderBy('a.id', 'DESC')
								->setMaxResults($page)
								->getQuery();
	 
		$query->setFirstResult(($page-1) * $nombreParPage)
			  ->setMaxResults($nombreParPage);

		return new Paginator($query);
	}
}
