<?php

namespace Postfix\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function last_logged_in()
	{
		$time = new \DateTime;
		$time->sub(new \DateInterval('PT2M'));
		return $this->createQueryBuilder('a')
							->where('a.last_logged_in > :time')
							->setParameter('time' , $time)
							->getQuery()
							->getResult();

	}
	public function incomingList()
	{
		return $this->createQueryBuilder('a')
							->where('a.roles NOT LIKE :role_partner AND a.roles NOT LIKE :role_super_admin')
							->setParameter('role_partner' , '%"ROLE_PARTNER"%')
							->setParameter('role_super_admin' , '%"ROLE_SUPER_ADMIN"%')
							->orderBy('a.id', 'DESC')
							->getQuery()
							->getResult();

	}
	public function UsersQuickList($nombreParPage , $page)
	{
		if ($page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
	 
		$query = $this->createQueryBuilder('a')
								->orderBy('a.id', 'DESC')
								->setMaxResults($page)
								->getQuery();
	 
		$query->setFirstResult(($page-1) * $nombreParPage)
			  ->setMaxResults($nombreParPage);

		return new Paginator($query);
	}
}
