<?php

namespace Postfix\MailboxBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Postfix\MailboxBundle\Entity\Mailbox;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
	public function getSecondaryAliases(Mailbox $mailbox)
	{
		return $this->createQueryBuilder('r')
								->leftJoin('r.creator', 'c')
								->addSelect('c')
								->where('r.destination LIKE :alias')
								->andWhere('r.source NOT LIKE :alias')
								->setParameter('alias', $mailbox->getMail())
								->orderBy('r.source' , 'ASC')
								->getQuery()
								->getResult();
	}
}
