<?php

namespace Postfix\DomainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function paginedList($limit, $page)
	{
		if ($page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}

		$query = $this->createQueryBuilder('c')
		->orderBy('c.name', 'ASC')
		->getQuery();

		$query->setFirstResult(($page-1) * $limit)
		->setMaxResults($limit);

		return new Paginator($query);
	}
}
